/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr;

import hris.ConnectionManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;

/**
 *
 * @author i5
 */
public class payr extends javax.swing.JPanel {

    /**
     * Creates new form payr
     */
     Connection con;
    Statement stmt;
    ResultSet rs;
    DefaultTableModel model;
    public payr() {
        initComponents();
        String ref = generateReferenceNumber();
        ref_num.setText(ref);
    }
        public static String generateReferenceNumber() {
               // Prefix
               String prefix = "REF";

               // Current date and time
               SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMddHHmmssSSS");
               String dateTime = sdf.format(new Date());

               // Random number
               Random random = new Random();
               int randomNumber = random.nextInt(1000); // Generates a random number between 0 and 999

               // Combine prefix, dateTime, and random number to create the reference number
               String referenceNumber = String.format("%s-%s-%03d", prefix, dateTime, randomNumber);

               return referenceNumber;
           }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        ref_num = new javax.swing.JTextField();
        management = new javax.swing.JTextField();
        emp_number = new javax.swing.JTextField();
        grade = new javax.swing.JTextField();
        emp_name = new javax.swing.JTextField();
        pagibig = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        sss = new javax.swing.JTextField();
        philhealth = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDate3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtDate4 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTabbedPane1.setBackground(java.awt.Color.white);

        jPanel10.setBackground(java.awt.Color.white);
        jPanel10.setPreferredSize(new java.awt.Dimension(1098, 688));
        jPanel10.setLayout(null);

        jLabel6.setText("Employee number:");
        jPanel10.add(jLabel6);
        jLabel6.setBounds(10, 11, 100, 16);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel10.add(email);
        email.setBounds(110, 90, 140, 30);

        jLabel7.setText("Employee Name:");
        jPanel10.add(jLabel7);
        jLabel7.setBounds(260, 10, 90, 16);

        jLabel9.setText("Department:");
        jPanel10.add(jLabel9);
        jLabel9.setBounds(10, 60, 74, 16);

        jLabel10.setText("Email:");
        jPanel10.add(jLabel10);
        jLabel10.setBounds(10, 100, 50, 16);

        jLabel11.setText("Job Status:");
        jPanel10.add(jLabel11);
        jLabel11.setBounds(260, 100, 90, 16);

        jLabel17.setText("SSS:");
        jPanel10.add(jLabel17);
        jLabel17.setBounds(610, 10, 60, 16);

        jLabel18.setText("Phil-health:");
        jPanel10.add(jLabel18);
        jLabel18.setBounds(610, 60, 80, 16);

        jLabel19.setText("Pag-ibig:");
        jPanel10.add(jLabel19);
        jLabel19.setBounds(610, 100, 70, 16);

        jLabel21.setText("Grade:");
        jPanel10.add(jLabel21);
        jLabel21.setBounds(260, 60, 70, 16);
        jPanel10.add(jSeparator3);
        jSeparator3.setBounds(10, 130, 1060, 10);

        jButton12.setText("Update Payslip Information");
        jPanel10.add(jButton12);
        jButton12.setBounds(100, 440, 229, 23);

        jButton13.setText("Generate Payslip");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton13);
        jButton13.setBounds(350, 440, 239, 23);

        jLabel33.setText("REFERENCE NUMBER:");
        jPanel10.add(jLabel33);
        jLabel33.setBounds(600, 440, 150, 20);

        jScrollPane2.setBackground(java.awt.Color.white);
        jScrollPane2.setToolTipText("");
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reference Number", "Date", "Department", "Employee Name", "Employee ID", "Status", "Modified by", "Date Modified"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel10.add(jScrollPane2);
        jScrollPane2.setBounds(200, 485, 860, 111);
        jPanel10.add(jSeparator5);
        jSeparator5.setBounds(10, 100, 1060, 0);

        jLabel34.setText("REFERENCE NUMBER:");
        jPanel10.add(jLabel34);
        jLabel34.setBounds(11, 485, 115, 16);

        jLabel35.setText("Employee number:");
        jPanel10.add(jLabel35);
        jLabel35.setBounds(11, 527, 100, 16);

        jButton16.setText("Update Payment Information");
        jPanel10.add(jButton16);
        jButton16.setBounds(11, 573, 184, 23);
        jPanel10.add(jTextField11);
        jTextField11.setBounds(21, 501, 161, 22);
        jPanel10.add(jTextField12);
        jTextField12.setBounds(21, 547, 161, 22);

        ref_num.setEditable(false);
        jPanel10.add(ref_num);
        ref_num.setBounds(760, 440, 233, 22);

        management.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managementActionPerformed(evt);
            }
        });
        jPanel10.add(management);
        management.setBounds(110, 50, 140, 30);

        emp_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_numberActionPerformed(evt);
            }
        });
        emp_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emp_numberKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emp_numberKeyTyped(evt);
            }
        });
        jPanel10.add(emp_number);
        emp_number.setBounds(110, 10, 140, 30);

        grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeActionPerformed(evt);
            }
        });
        jPanel10.add(grade);
        grade.setBounds(360, 50, 170, 30);
        jPanel10.add(emp_name);
        emp_name.setBounds(360, 10, 170, 30);
        jPanel10.add(pagibig);
        pagibig.setBounds(720, 90, 170, 30);
        jPanel10.add(status);
        status.setBounds(360, 90, 170, 30);
        jPanel10.add(sss);
        sss.setBounds(720, 10, 170, 30);

        philhealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                philhealthActionPerformed(evt);
            }
        });
        jPanel10.add(philhealth);
        philhealth.setBounds(720, 50, 170, 30);
        jPanel10.add(jSeparator4);
        jSeparator4.setBounds(10, 469, 1060, 10);

        jTabbedPane1.addTab("Payroll", jPanel10);

        jPanel11.setBackground(java.awt.Color.white);
        jPanel11.setPreferredSize(new java.awt.Dimension(1098, 688));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel2.setText("REFERENCE NUMBER:");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel8.setText("FROM:");

        txtDate3.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtDate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDate3ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        jButton7.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton7.setText("...");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel12.setText("TO:");

        txtDate4.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtDate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDate4ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton8.setText("...");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton3.setText("VIEW");

        jButton9.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton9.setText("DISPUTE");

        jButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton4.setText("DOWNLOAD");

        jTable2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REFERENCE NUMBER", "PAYOUT DATE", "DOCUMENT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setPreferredSize(new java.awt.Dimension(825, 768));
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDate3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDate4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)))
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE)
                .addGap(55, 55, 55))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton7)
                                .addComponent(txtDate4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton8)
                                .addComponent(jLabel12)
                                .addComponent(jLabel8))
                            .addGap(3, 3, 3))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                            .addComponent(jButton9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton4)))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("Payslip Record", jPanel11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDate3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDate3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtDate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDate4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDate4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void managementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managementActionPerformed

    private void emp_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_numberActionPerformed
        //here id  
        // TODO add your handling code here:
        
    }//GEN-LAST:event_emp_numberActionPerformed

    private void gradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeActionPerformed

    private void emp_numberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp_numberKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_emp_numberKeyTyped

    private void emp_numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp_numberKeyReleased
  String id = emp_number.getText().trim();
            // Call the method to retrieve employee information based on the ID
            if(id.isEmpty()){
                emp_name.setText("");
                management.setText("");
                email.setText("");
                grade.setText("");
                status.setText("");
                sss.setText("");
                philhealth.setText("");
                pagibig.setText("");
            }
            getEmployeeByID(id);        // TODO add your handling code here:
    }//GEN-LAST:event_emp_numberKeyReleased

    private void philhealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_philhealthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_philhealthActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
//            insertPayroll();                    // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed
    
   
    
//        private static void insertPayslip(Connection con, int employeeId, double basicPay, double allowances, double deductions) throws SQLException {
//              // Perform payslip calculation here
//              // You can reuse the previous logic to calculate basic pay from DTR
//              // For simplicity, let's assume basicPay is calculated based on DTR
//              double netPay = calculateBasicPayFromDTR(con, employeeId) + allowances - deductions;
//
//              // Insert into payslip table
//              String payslipInsert = "INSERT INTO payslip (employee_id, basic_pay, allowances, deductions, net_pay) VALUES (?, ?, ?, ?, ?)";
//              try (PreparedStatement payslipStmt = con.prepareStatement(payslipInsert)) {
//                  payslipStmt.setInt(1, employeeId);
//                  payslipStmt.setDouble(2, basicPay);
//                  payslipStmt.setDouble(3, allowances);
//                  payslipStmt.setDouble(4, deductions);
//                  payslipStmt.setDouble(5, netPay);
//
//                  payslipStmt.executeUpdate();
//              }
//          }
    
    private void getEmployeeByID(String id){
    // Implement the logic to retrieve employee information based on the ID
    // You can perform database queries or other operations here
    // For example:
    try {
        con = ConnectionManager.getConnection();
            stmt = con.createStatement();

        // Execute a SELECT query to retrieve data from the "emp_info" table based on the employee ID
       String query = "SELECT emp_info.*, cred.* FROM emp_info INNER JOIN cred ON emp_info.EmployeeID = cred.EmployeeID WHERE emp_info.EmployeeID = ?";
        PreparedStatement pstmt = con.prepareStatement(query);
        pstmt.setString(1, id);
        rs = pstmt.executeQuery();
        
        while(rs.next()){
//            management.setText(rs.getString());
               emp_name.setText(rs.getString("emp_fname") + " " + rs.getString("emp_lname"));
                email.setText(rs.getString("cEmail"));
                grade.setText("98");
                management.setText(rs.getString("emp_department"));
                status.setText(rs.getString("Status"));
                sss.setText(rs.getString("emp_sss"));
                philhealth.setText(rs.getString("emp_philhealth"));
                pagibig.setText(rs.getString("emp_pagibig"));
 }
         
        
        // Process the ResultSet and display or handle the retrieved employee information
        // For example, you can display the information in JTextFields or other components

    } catch (SQLException ex) {
        ex.printStackTrace(); // Handle SQL exceptions
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JTextField emp_name;
    private javax.swing.JTextField emp_number;
    private javax.swing.JTextField grade;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField management;
    private javax.swing.JTextField pagibig;
    private javax.swing.JTextField philhealth;
    private javax.swing.JTextField ref_num;
    private javax.swing.JTextField sss;
    private javax.swing.JTextField status;
    private javax.swing.JTextField txtDate3;
    private javax.swing.JTextField txtDate4;
    // End of variables declaration//GEN-END:variables
}
