/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr;

/**
 *
 * @author i5
 */
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import hris.ConnectionManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;

public class payr extends javax.swing.JPanel {

    /**
     * Creates new form payr
     */
    public payr() {
        initComponents();
        
        loadData();
        String refNumber = generateReferenceNumber();
        jTextField13.setText(refNumber);
    }
        Connection con;
    Statement stmt;
    PreparedStatement pst;
    ResultSet rs;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDate3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtDate4 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTabbedPane1.setBackground(java.awt.Color.white);

        jPanel10.setBackground(java.awt.Color.white);
        jPanel10.setPreferredSize(new java.awt.Dimension(1098, 688));
        jPanel10.setLayout(null);

        jLabel6.setText("Employee number:");
        jPanel10.add(jLabel6);
        jLabel6.setBounds(10, 11, 100, 16);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel10.add(jTextField1);
        jTextField1.setBounds(120, 10, 140, 30);

        jLabel7.setText("Employee Name:");
        jPanel10.add(jLabel7);
        jLabel7.setBounds(270, 10, 90, 16);

        jLabel10.setText("Email:");
        jPanel10.add(jLabel10);
        jLabel10.setBounds(10, 50, 50, 16);

        jLabel11.setText("Job Status:");
        jPanel10.add(jLabel11);
        jLabel11.setBounds(550, 10, 70, 16);

        jLabel17.setText("SSS:");
        jPanel10.add(jLabel17);
        jLabel17.setBounds(550, 50, 30, 16);

        jLabel18.setText("Phil-health:");
        jPanel10.add(jLabel18);
        jLabel18.setBounds(800, 10, 61, 16);

        jLabel19.setText("Pag-ibig:");
        jPanel10.add(jLabel19);
        jLabel19.setBounds(800, 50, 48, 16);

        jLabel20.setText("Department:");
        jPanel10.add(jLabel20);
        jLabel20.setBounds(270, 50, 66, 16);
        jPanel10.add(jSeparator3);
        jSeparator3.setBounds(10, 469, 1060, 10);

        jButton12.setText("Update Payslip Information");
        jPanel10.add(jButton12);
        jButton12.setBounds(147, 440, 229, 23);

        jButton13.setText("Generate Payslip");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton13);
        jButton13.setBounds(382, 440, 239, 23);

        jLabel33.setText("REFERENCE NUMBER:");
        jPanel10.add(jLabel33);
        jLabel33.setBounds(631, 444, 115, 16);

        jScrollPane2.setBackground(java.awt.Color.white);
        jScrollPane2.setToolTipText("");
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reference Number", "Date", "Department", "Employee Name", "Employee ID", "Status", "Modified by", "Date Modified"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel10.add(jScrollPane2);
        jScrollPane2.setBounds(200, 485, 860, 111);
        jPanel10.add(jSeparator5);
        jSeparator5.setBounds(10, 81, 1060, 3);

        jLabel34.setText("REFERENCE NUMBER:");
        jPanel10.add(jLabel34);
        jLabel34.setBounds(11, 485, 115, 16);

        jLabel35.setText("Employee number:");
        jPanel10.add(jLabel35);
        jLabel35.setBounds(11, 527, 100, 16);

        jButton16.setText("Update Payment Information");
        jPanel10.add(jButton16);
        jButton16.setBounds(11, 573, 184, 23);
        jPanel10.add(jTextField11);
        jTextField11.setBounds(21, 501, 161, 22);
        jPanel10.add(jTextField12);
        jTextField12.setBounds(21, 547, 161, 22);

        jTextField13.setEditable(false);
        jPanel10.add(jTextField13);
        jTextField13.setBounds(741, 441, 233, 22);
        jPanel10.add(jTextField4);
        jTextField4.setBounds(120, 50, 140, 30);
        jPanel10.add(jTextField5);
        jTextField5.setBounds(370, 10, 140, 30);
        jPanel10.add(jTextField7);
        jTextField7.setBounds(370, 50, 140, 30);
        jPanel10.add(jTextField8);
        jTextField8.setBounds(620, 10, 140, 30);
        jPanel10.add(jTextField10);
        jTextField10.setBounds(620, 50, 140, 30);
        jPanel10.add(jTextField14);
        jTextField14.setBounds(870, 10, 140, 30);
        jPanel10.add(jTextField15);
        jTextField15.setBounds(870, 50, 140, 30);

        jTabbedPane1.addTab("Payroll", jPanel10);

        jPanel11.setBackground(java.awt.Color.white);
        jPanel11.setPreferredSize(new java.awt.Dimension(1098, 688));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel2.setText("REFERENCE NUMBER:");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel8.setText("FROM:");

        txtDate3.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtDate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDate3ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        jButton7.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton7.setText("...");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel12.setText("TO:");

        txtDate4.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtDate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDate4ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton8.setText("...");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton3.setText("VIEW");

        jButton9.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton9.setText("DISPUTE");

        jButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton4.setText("DOWNLOAD");

        jTable2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REFERENCE NUMBER", "PAYOUT DATE", "DOCUMENT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setPreferredSize(new java.awt.Dimension(825, 768));
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDate3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDate4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)))
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE)
                .addGap(55, 55, 55))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton7)
                                .addComponent(txtDate4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton8)
                                .addComponent(jLabel12)
                                .addComponent(jLabel8))
                            .addGap(3, 3, 3))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                            .addComponent(jButton9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton4)))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("Payslip Record", jPanel11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDate3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDate3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtDate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDate4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDate4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        try {
        con = ConnectionManager.getConnection();
        
        // Retrieve basic_pay from the salary table
        String basicPayQuery = "SELECT basic_pay FROM salary WHERE emp_id = ?";
        pst = con.prepareStatement(basicPayQuery);
        pst.setInt(1, Integer.parseInt(jTextField1.getText())); // employee_id
        ResultSet basicPayResult = pst.executeQuery();
        
        // Check if basic_pay data is retrieved
        if (basicPayResult.next()) {
            double basicPay = basicPayResult.getDouble("basic_pay");

            // Get current date
            Calendar cal = Calendar.getInstance();
            int dayOfMonth = cal.get(Calendar.DAY_OF_MONTH);
            int payoutDate;
            
            // Calculate payout date based on the day of the month
            if (dayOfMonth >= 1 && dayOfMonth <= 15) {
                payoutDate = 25;
                basicPay = basicPay / 2.0;
            } else {
                payoutDate = 10;
                basicPay = basicPay / 2.0;
                // Check if it's the last day of the month
                if (dayOfMonth == cal.getActualMaximum(Calendar.DAY_OF_MONTH)) {
                    // Move to next month
                    cal.add(Calendar.MONTH, 1);
                }
            }
            int hours = 120;
            double payperhour = basicPay/hours;
           
            // Construct payout date string (YYYY-MM-DD)
            String month = String.format("%02d", cal.get(Calendar.MONTH) + 1); // Adding 1 because Calendar.MONTH is zero-based
            String year = String.valueOf(cal.get(Calendar.YEAR));
            String payoutDateString = String.format("%s-%s-%02d", year, month, payoutDate);

            // Prepare the INSERT statement for payslip table
            String payslipInsertQuery = "INSERT INTO payslip (ref_id, employee_id, payout_date, basic_pay) VALUES (?, ?, ?, ?)";
            pst = con.prepareStatement(payslipInsertQuery);

            // Set values from JTextFields
            pst.setString(1, jTextField13.getText()); // ref_id
            pst.setInt(2, Integer.parseInt(jTextField1.getText())); // employee_id
            pst.setString(3, payoutDateString); // payout_date
            pst.setDouble(4, basicPay); // basic_pay

            // Execute the INSERT statement
            int rowsInserted = pst.executeUpdate();
            if (rowsInserted > 0) {
                System.out.println("A new row has been inserted into the payslip table.");
                loadData();
            }
        } else {
            System.out.println("Error: No basic_pay found for the employee ID.");
        }
    } catch (SQLException e) {
        System.out.println("Error inserting data into payslip table: " + e.getMessage());
    }   
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        String employeeID = jTextField1.getText();
    
    try {
        // Establish connection
        con = ConnectionManager.getConnection();
        
        // Prepare SQL statement to retrieve data based on EmployeeID
        String sql = "SELECT * FROM emp_info WHERE EmployeeID = ?";
        pst = con.prepareStatement(sql);
        
        // Set the EmployeeID parameter
        pst.setString(1, employeeID);
        
        // Execute the query
        rs = pst.executeQuery();
        
        // Check if any data is retrieved
        if (rs.next()) {
            // Populate JTextFields with retrieved data
            jTextField4.setText(rs.getString("emp_email")); // email
            jTextField5.setText(rs.getString("emp_lname")); // emp_name
            jTextField7.setText(rs.getString("emp_department")); // department
            jTextField8.setText(rs.getString("emp_status")); // job_status
            jTextField10.setText(rs.getString("emp_SSS")); // sss
            jTextField14.setText(rs.getString("emp_philhealth")); // phil_health
            jTextField15.setText(rs.getString("emp_pagibig")); // pag_ibig
        } else {
            // If no data is retrieved, clear JTextFields
            jTextField4.setText(""); // email
            jTextField5.setText(""); // emp_name
            jTextField7.setText(""); // department
            jTextField8.setText(""); // job_status
            jTextField10.setText(""); // sss
            jTextField14.setText(""); // phil_health
            jTextField15.setText(""); // pag_ibig
        }
    } catch (SQLException e) {
        System.out.println("Error fetching data from emp_info table: " + e.getMessage());
    }
    }//GEN-LAST:event_jTextField1KeyReleased
    
    private void loadData(){
        try {
                con = ConnectionManager.getConnection(); // Establish a connection to the database
                stmt = con.createStatement(); // Create a statement object for executing SQL queries

                rs = stmt.executeQuery("SELECT * from payslip"); // Execute a SELECT query to retrieve data from the "cred" table

                // Create a DefaultTableModel with column names
                String[] columnNames = {"EMPLOYEE ID", "REFFERENCE NUMBER", "PAYOUT DATE"};
                DefaultTableModel model = new DefaultTableModel(columnNames, 0); // Initialize a DefaultTableModel with column names

                while (rs.next()) {
                    // Iterate over the ResultSet and add each row to the DefaultTableModel
                    model.addRow(new Object[]{
                        rs.getString("employee_id"),
                        rs.getString("ref_id"),
                        rs.getString("payout_date"),
                    });
                }

                // Set the model to your JTable to display the data
                jTable2.setModel(model);

            } catch (SQLException ex) {
                ex.printStackTrace(); // Handle SQL exceptions
            }
    }

public static String generateReferenceNumber() {
        // Prefix
        String prefix = "REF";
        
        // Current date and time
        SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMddHHmmssSSS");
        String dateTime = sdf.format(new Date());
        
        // Random number
        Random random = new Random();
        int randomNumber = random.nextInt(1000); // Generates a random number between 0 and 999
        
        // Combine prefix, dateTime, and random number to create the reference number
        String referenceNumber = String.format("%s-%s-%03d", prefix, dateTime, randomNumber);
        
        return referenceNumber;
    }   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField txtDate3;
    private javax.swing.JTextField txtDate4;
    // End of variables declaration//GEN-END:variables
}
